server:
  port: 9080

app:
  schedule:
    updateRules: "0/59 * * * * *"

spring:
  application:
    name: Fraud Rule Api
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/frauddb
    username: postgres
    password: postgres
    hikari:
      schema: fraud
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: fraud

logging:
  level:
    root: info
    org:
      flywaydb: DEBUG