name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 25 (Temurin)
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven

      # Build and run tests
      - name: Build with Maven
        run: mvn -B clean verify

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Extract project version from pom.xml
      - name: Extract project version
        id: vars
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Build and push image to both registries
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/your-app:${{ env.VERSION }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/your-app:latest
            ghcr.io/${{ github.repository_owner.toLowerCase() }}/your-app:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner.toLowerCase() }}/your-app:latest
